export const testCases=[
    {
        type:"+",
        index:1,
        inputArray:[20,30,40,50],
        elementToSearch:30,
        output:1
    },
    {
        type:"+",
        index:2,
        inputArray:[1,20,25,65],
        elementToSearch:65,
        output:3
    },
    {
        type:"-",
        index:3,
        inputArray:[1,20,25,65],
        elementToSearch:100,
        output:-1
    }
]